# Generated by Django 2.2.2 on 2019-06-19 21:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShadertoyShader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shader_id', models.CharField(db_index=True, max_length=32, verbose_name='Shader ID')),
                ('date_visited', models.DateTimeField(db_index=True, verbose_name='Last seen at')),
                ('shader_json', jsonfield.fields.JSONField(default=dict, verbose_name='JSON data')),
                ('date_published', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Published at')),
                ('username', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='User')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description')),
                ('tags', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Tags')),
                ('num_views', models.IntegerField(blank=True, default=None, null=True, verbose_name='#Views')),
                ('num_likes', models.IntegerField(blank=True, default=None, null=True, verbose_name='#Likes')),
                ('num_passes', models.IntegerField(blank=True, default=None, null=True, verbose_name='#Passes')),
                ('num_characters', models.IntegerField(blank=True, default=None, null=True, verbose_name='#Characters')),
            ],
            options={
                'unique_together': {('shader_id', 'date_visited')},
            },
        ),
    ]
