# Generated by Django 2.2.2 on 2019-06-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadertoy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadertoyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shader_id', models.CharField(db_index=True, max_length=32, verbose_name='Shader ID')),
                ('date_published', models.DateTimeField(verbose_name='Published at')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='Username')),
                ('userpicture', models.CharField(max_length=256, verbose_name='User picture URL')),
                ('text', models.TextField(verbose_name='Text')),
                ('comment_id', models.CharField(max_length=32, verbose_name='Comment ID')),
                ('hidden', models.BooleanField(verbose_name='Hidden')),
            ],
        ),
    ]
