# Generated by Django 2.1.4 on 2018-12-17 11:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShadertoyShader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shader_id', models.CharField(max_length=32, verbose_name='Shader ID')),
                ('shader_json', jsonfield.fields.JSONField(default=dict, verbose_name='JSON data')),
            ],
        ),
    ]
