# Generated by Django 2.1.4 on 2018-12-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadertoyshader',
            name='date_published',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Published'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_characters',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Characters'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_likes',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Likes'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_likes_per_day',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='#Likes/d'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_passes',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Passes'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_views',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Views'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_views_per_day',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='#Views/d'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='User'),
        ),
    ]
