# Generated by Django 2.1.4 on 2018-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaders', '0002_auto_20181218_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_chars_code',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Code chars'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_chars_comment',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Comment chars'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_lines_blank',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Blank lines'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_lines_code',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Code lines'),
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_lines_comment',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Comment lines'),
        ),
    ]
