# Generated by Django 2.1.4 on 2018-12-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaders', '0003_auto_20181218_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadertoyshader',
            name='num_lines',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='#Lines'),
        ),
    ]
