# Generated by Django 2.1.4 on 2018-12-31 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shaders', '0004_shadertoyshader_num_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_json', jsonfield.fields.JSONField(default=dict, verbose_name='JSON data')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
        ),
        migrations.AddField(
            model_name='shadertoyshader',
            name='code_stats',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='shaders.CodeStatsModel', verbose_name='Code statistics'),
        ),
    ]
